### PR TITLE
Update de.properties

### PR DESCRIPTION
**Pull request by tooomm**
Your welcome :)

### CODE REVIEW

**Comment by mkiol** [comment]
Thanks!

**Comment by tooomm** [comment]
Does it makes sense/it is possible to have all the untranslated strings in other languages as well?
Like this for the `zh-CN.properties` language file for example:
```
 open=打开
 Open_file=打开文件
 Open_folder=打开文件夹
 Mark_as_read=
 Number_of_unread_messages=未读消息数量：
 Number_of_new_messages=
 New_message=新消息！
 New_messages=
 New_message_from=新消息来自
 New_article=新文章！
 New_articles=
 New_article_from=新文章来自
 File=文件
 Folder=文件夹
```

To show interested people and native speakers what they can easily add to help you and properly use the addon in their own language completely.

Btw: PR 139 adds a `+` at the beginning of all lines of the **Italian locale**... just in case that this is a problem...
https://github.com/mkiol/GNotifier/blob/master/source/locale/it-IT.properties

**Comment by mkiol** [comment]
> Does it makes sense/it is possible to have all the untranslated strings in other languages as well?

It definitely helps translators, so it make sense. The only think I need is some script that automate it. I don't want to update 32 files manually :-)

**Comment by tooomm** [comment]
Haha, yes. I wasn't sure though, if empty strings lead to any problems...

**Pull request merged**
