### PR TITLE
Update fr.properties

### PR DESCRIPTION
**Pull request by gnafron**
I've translated your plugin into French.
Could you update the translation please ?

### CODE REVIEW

**Comment by mkiol** [comment]
Please check the [EN translation file](https://github.com/mkiol/GNotifier/blob/master/source/locale/en.properties)? There is one additional string "Mark_as_read" not translated in your file. I would be grateful if you could translate it as well. Thanks!

**Comment by gnafron** [comment]
Translated !

**Comment by mkiol** [comment]
Thank you!

**Comment by mkiol** [comment]
I added new [lines](https://github.com/mkiol/GNotifier/blob/master/source/locale/en.properties). Would be grateful if you could update your translation.

**Pull request merged**
