### PR TITLE
linux: Provide both image and icon to servers when possible

### PR DESCRIPTION
**Pull request by sardemff7**
First try for the feature discussed in #67.

### CODE REVIEW

**Comment by mkiol** [comment]
I see following error:
`console.error: gnotifier: 
  Message: Error: not a ctypes type
  Stack:
    linux.checkAvailable@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-oonoa6xbjznvlq-at-jetpack/gnotifier/lib/linux.js:219:40
`

so probably something is wrong with this declaration:
<code>
notify_notification_set_hint = libc.declare(
          "notify_notification_set_hint", ctypes.default_abi, ctypes.void,
          struct_notification.ptr, ctypes.char.ptr, struct_gvariant.ptr);
</code>

**Comment by sardemff7** [comment]
I never used this JS API (libc) so yes. Where is the documentation?

**Comment by sardemff7** [comment]
Ok, I found the error (`void` instead of `void_t`).

I also updated the icon/image code to match the spec, and it should work fine for KDE too, since the `image-path`/`image_path` hint is indeed parsed as an URI.

**Comment by mkiol** [comment]
First of all, thank you for trying to fix it. Now, it works on all servers with spec ver 1.1, so including my KDE DE :-)

Unfortunately I see few issues on distros with 1.2 spec servers. I've made tests on:
* Mint 17.2 with Cinnamon
* Ubuntu 15.4 with GNOME 3.16.3

Results are:
* on Mint, libnotify sends DBus notification, but server do not reply -> libnotify returns error to Gnotifier
* on Ubuntu (with Gnome) notification appears with nice FF icon, but image is missing - I'm guessing GNOME can't display at the same time both icon & image.

**Comment by sardemff7** [comment]
Ok.
First, to my knowledge, only one server can display both image and icon: eventd, which is my server.

The Mint error is strange, do you know which server they are using? Cinnamon? MATE?

The Ubuntu error is… an implementation error. When the server cannot display both, it should pick the `image-path` hint, not the icon.
From the GNOME-Shell code, they do that on purpose, breaking their own spec. And since they really want to break everything, they only ever use `image-path` as … a path! While the spec is explicit that it should be an URI.

I will then just put *either* the icon or the image for servers lacking the capability, and do my best regarding URIs.

**Comment by sardemff7** [comment]
Simple solution: I expect servers with the `x-eventd-overlay-icon` capability (so they can display both) to be using the 1.2 spec and to support it strictly (at *least* to support URIs everywhere).
Does that suit you?

**Comment by mkiol** [comment]
It seems very rational to me. Thank you.

**Pull request merged**
