### PR TITLE
TB: Change Notification Title To Include Author

### PR DESCRIPTION
**Pull request by amayer5125**
Notification title will look like "New Message From NAME HERE"
Name falls back to full email address
Notification body is now only subject line

### CODE REVIEW

**Comment by amayer5125** [comment]
@mkiol I didnt update any other locals with the "New Message From" text. I only speak english. If this is something you would like me to do I am willing to use Google Translate. But from what I hear this isnt entierly reliable.

**Comment by mkiol** [comment]
Thank for pull request. I'm about to merge but see one issue. When author name is formed from non-ascii characters, result is quite ugly. Can you look at this?

screenshot from 2015-06-27 12 14 49

**Comment by amayer5125** [comment]
@mkio I will look into it.

**Comment by amayer5125** [comment]
@mkiol It looks like you just have html `&lt;` and `&gt;` in your email header. I did a quick replace for each of these and made a new commit. I believe this should solve your problem.

**Comment by mkiol** [comment]
Don't bother about `&lt;` and `&gt;` - this is bug inside linux.js that I have to fix.

Being more specific, when author string has non-ascii characters, `/^["']?[\w\s]+["']?\s<.+?>$/.test(author)` returns `false`.

I did tests following tests:
1. `Gnotifier <gnotifier@mkiol.net>` => returns `true`
2. `Zażółć gęślą jaźń <gnotifier@mkiol.net>` => returns `false`
3. `Alex Mayer <gnotifier@mkiol.net>` => returns `true`
4. `Michał <gnotifier@mkiol.net>` => returns `false`

**Comment by amayer5125** [comment]
@mkiol Ill do some research. Ive never looked into matching non-ascii charaters. Im familiar with unicode but Im not sure how tidy it is as far as accented letters go.

**Comment by amayer5125** [comment]
@mkiol I did some tests against the unicode email you provided and I believe I have it working. Can you please test and let me know what you find?

**Comment by mkiol** [comment]
Works flawlessly! I made some tests with Greek, Georgian and Chinese alphabet and all were successfully passed.

**Comment by amayer5125** [comment]
Will you be uploading this to mozilla addons?

**Comment by mkiol** [comment]
I will but.. there are few newly discovered bugs that I have to fix before that.

**Comment by amayer5125** [comment]
Ok. I dont know much about these addons but if you need any help feel free to mention me in issues.

**Comment by mkiol** [comment]
Thanks for be willing in helping me, much appreciated :-)

**Pull request merged**
